In [7]:
# 데이터 확인 작업
import pandas as pd

In [8]:
busan_food = pd.read_csv('../Data_Store/Processed_data/busan_food.csv', encoding='utf-8')

In [9]:
busan_food.drop(['Unnamed: 0'], axis = 1, inplace = True)

In [10]:
busan_food

,번호,개방서비스명,개방서비스ID,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,공장판매직종업원수,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지
0,1,식품제조가공업,07_22_11_P,3290000,3290000-106-2002-01621,20020913,NaN,1,영업/정상,1,...,0.0,5.0,자가,NaN,NaN,N,5.40,NaN,NaN,NaN
1,2,식품제조가공업,07_22_11_P,3350000,3350000-106-2006-00015,20061213,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,0.00,NaN,NaN,NaN
2,3,식품제조가공업,07_22_11_P,3360000,3360000-106-2006-00006,20060605,NaN,1,영업/정상,1,...,0.0,21.0,임대,NaN,NaN,N,0.00,NaN,NaN,NaN
3,4,식품제조가공업,07_22_11_P,3360000,3360000-106-2001-00080,20010409,NaN,1,영업/정상,1,...,0.0,70.0,NaN,NaN,NaN,N,0.00,NaN,NaN,NaN
4,5,식품제조가공업,07_22_11_P,3380000,3380000-106-2017-00005,20170621,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,6.15,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4733,4734,식품제조가공업,07_22_11_P,3300000,3300000-106-1998-00001,19981104,NaN,3,폐업,2,...,0.0,0.0,NaN,NaN,NaN,N,0.00,NaN,NaN,NaN
4734,4735,식품제조가공업,07_22_11_P,3300000,3300000-106-1998-00134,19981118,NaN,3,폐업,2,...,0.0,0.0,NaN,NaN,NaN,N,0.00,NaN,NaN,NaN
4735,4736,식품제조가공업,07_22_11_P,3300000,3300000-106-1998-00158,19981202,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,0.00,NaN,NaN,NaN
4736,4737,식품제조가공업,07_22_11_P,3300000,3300000-106-1998-00015,19981215,NaN,3,폐업,2,...,0.0,0.0,NaN,NaN,NaN,N,0.00,NaN,NaN,NaN
4737,4738,식품제조가공업,07_22_11_P,3300000,3300000-106-1999-00664,19990325,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,0.00,NaN,NaN,NaN

In [11]:
busan_food.columns

Index(['번호', '개방서비스명', '개방서비스ID', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)',
       '위생업태명', '남성종사자수', '여성종사자수', '영업장주변구분명', '등급구분명', '급수시설구분명', '총종업원수',
       '본사종업원수', '공장사무직종업원수', '공장판매직종업원수', '공장생산직종업원수', '건물소유구분명', '보증액',
       '월세액', '다중이용업소여부', '시설총규모', '전통업소지정번호', '전통업소주된음식', '홈페이지'],
      dtype='object')

In [12]:
missing = busan_food.shape[0] - busan_food.count()
missing

번호              0
개방서비스명          0
개방서비스ID         0
개방자치단체코드        0
관리번호            0
인허가일자           0
인허가취소일자      4738
영업상태구분코드        0
영업상태명           0
상세영업상태코드        0
상세영업상태명         0
폐업일자         1374
휴업시작일자       4738
휴업종료일자       4738
재개업일자        4738
소재지전화         866
소재지면적         643
소재지우편번호        92
소재지전체주소         5
도로명전체주소      2182
도로명우편번호      2227
사업장명            0
최종수정시점          0
데이터갱신구분         0
데이터갱신일자         0
업태구분명         175
좌표정보(X)       242
좌표정보(Y)       242
위생업태명         175
남성종사자수       3858
여성종사자수       3859
영업장주변구분명     3223
등급구분명        3223
급수시설구분명      2932
총종업원수        4738
본사종업원수       1672
공장사무직종업원수    1651
공장판매직종업원수    1668
공장생산직종업원수    1617
건물소유구분명      2976
보증액          4424
월세액          4424
다중이용업소여부        0
시설총규모           0
전통업소지정번호     4738
전통업소주된음식     4738
홈페이지         4661
dtype: int64

In [13]:
newcol = ['개방서비스명','인허가일자', '인허가취소일자', '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '소재지면적', '소재지전체주소', '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)','위생업태명', '남성종사자수', '여성종사자수', '다중이용업소여부', '시설총규모']

In [17]:
busan_food_nor = busan_food[newcol]

In [19]:
busan_food_nor.head()

,개방서비스명,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,소재지면적,소재지전체주소,...,데이터갱신구분,데이터갱신일자,업태구분명,좌표정보(X),좌표정보(Y),위생업태명,남성종사자수,여성종사자수,다중이용업소여부,시설총규모
0,식품제조가공업,20020913,NaN,1,영업/정상,1,영업,NaN,140.89,부산광역시 부산진구 부전동 347-23번지,...,U,2019-10-09 02:40:00.0,식품제조가공업,387487.293836,186604.950533,식품제조가공업,NaN,NaN,N,5.40
1,식품제조가공업,20061213,NaN,1,영업/정상,1,영업,NaN,45.04,부산광역시 금정구 남산동 952-2번지,...,I,2018-08-31 23:59:59.0,식품제조가공업,389613.687786,199356.200345,식품제조가공업,NaN,NaN,N,0.00
2,식품제조가공업,20060605,NaN,1,영업/정상,1,영업,NaN,925.60,부산광역시 강서구 송정동 1761-6번지,...,I,2018-08-31 23:59:59.0,식품제조가공업,368550.469102,177696.068418,식품제조가공업,NaN,NaN,N,0.00
3,식품제조가공업,20010409,NaN,1,영업/정상,1,영업,NaN,"1,549.00",부산광역시 강서구 녹산동 97-5번지,...,I,2018-08-31 23:59:59.0,기타 식품제조가공업,372485.321697,181534.283375,기타 식품제조가공업,0.0,0.0,N,0.00
4,식품제조가공업,20170621,NaN,1,영업/정상,1,영업,NaN,235.68,부산광역시 수영구 망미동 206-11번지,...,I,2018-08-31 23:59:59.0,기타 식품제조가공업,392836.990685,188366.641615,기타 식품제조가공업,NaN,NaN,N,6.15

In [22]:
missing = busan_food_nor.shape[0] - busan_food_nor.count()

In [23]:
missing

개방서비스명         0
인허가일자          0
인허가취소일자     4738
영업상태구분코드       0
영업상태명          0
상세영업상태코드       0
상세영업상태명        0
폐업일자        1374
소재지면적        643
소재지전체주소        5
사업장명           0
최종수정시점         0
데이터갱신구분        0
데이터갱신일자        0
업태구분명        175
좌표정보(X)      242
좌표정보(Y)      242
위생업태명        175
남성종사자수      3858
여성종사자수      3859
다중이용업소여부       0
시설총규모          0
dtype: int64

In [24]:
busan_food_nor.columns

Index(['개방서비스명', '인허가일자', '인허가취소일자', '영업상태구분코드', '영업상태명', '상세영업상태코드',
       '상세영업상태명', '폐업일자', '소재지면적', '소재지전체주소', '사업장명', '최종수정시점', '데이터갱신구분',
       '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)', '위생업태명', '남성종사자수', '여성종사자수',
       '다중이용업소여부', '시설총규모'],
      dtype='object')

In [25]:
newcol = ['개방서비스명', '인허가일자','영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '소재지면적', '소재지전체주소', '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)', '위생업태명', '다중이용업소여부', '시설총규모']

In [26]:
newcol

['개방서비스명',
 '인허가일자',
 '영업상태구분코드',
 '영업상태명',
 '상세영업상태코드',
 '상세영업상태명',
 '폐업일자',
 '소재지면적',
 '소재지전체주소',
 '사업장명',
 '최종수정시점',
 '데이터갱신구분',
 '데이터갱신일자',
 '업태구분명',
 '좌표정보(X)',
 '좌표정보(Y)',
 '위생업태명',
 '다중이용업소여부',
 '시설총규모']

In [28]:
busan_food_nor = busan_food_nor[newcol]

In [29]:
busan_food_nor.head()

,개방서비스명,인허가일자,영업상태구분코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,소재지면적,소재지전체주소,사업장명,최종수정시점,데이터갱신구분,데이터갱신일자,업태구분명,좌표정보(X),좌표정보(Y),위생업태명,다중이용업소여부,시설총규모
0,식품제조가공업,20020913,1,영업/정상,1,영업,NaN,140.89,부산광역시 부산진구 부전동 347-23번지,동일식품,20191007163850,U,2019-10-09 02:40:00.0,식품제조가공업,387487.293836,186604.950533,식품제조가공업,N,5.40
1,식품제조가공업,20061213,1,영업/정상,1,영업,NaN,45.04,부산광역시 금정구 남산동 952-2번지,제빵소 작,20170726144834,I,2018-08-31 23:59:59.0,식품제조가공업,389613.687786,199356.200345,식품제조가공업,N,0.00
2,식품제조가공업,20060605,1,영업/정상,1,영업,NaN,925.60,부산광역시 강서구 송정동 1761-6번지,에스엔푸드(SN FOOD),20170102110559,I,2018-08-31 23:59:59.0,식품제조가공업,368550.469102,177696.068418,식품제조가공업,N,0.00
3,식품제조가공업,20010409,1,영업/정상,1,영업,NaN,"1,549.00",부산광역시 강서구 녹산동 97-5번지,진해물산(주),20170502103713,I,2018-08-31 23:59:59.0,기타 식품제조가공업,372485.321697,181534.283375,기타 식품제조가공업,N,0.00
4,식품제조가공업,20170621,1,영업/정상,1,영업,NaN,235.68,부산광역시 수영구 망미동 206-11번지,커피덕트(COFFEE DUCT),20180426164041,I,2018-08-31 23:59:59.0,기타 식품제조가공업,392836.990685,188366.641615,기타 식품제조가공업,N,6.15

In [84]:
busan_food_cafe = busan_food_nor[busan_food_nor['사업장명'].str.findall(pat = '.*커피|카페|로스터리|로스팅.*').str.len() != 0]

In [87]:
busan_food_cafe.reset_index(drop = True, inplace = True)

In [89]:
busan_food_cafe.shape

(169, 19)

In [90]:
busan_food_cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 19 columns):
개방서비스명      169 non-null object
인허가일자       169 non-null int64
영업상태구분코드    169 non-null int64
영업상태명       169 non-null object
상세영업상태코드    169 non-null int64
상세영업상태명     169 non-null object
폐업일자        64 non-null float64
소재지면적       165 non-null object
소재지전체주소     169 non-null object
사업장명        169 non-null object
최종수정시점      169 non-null int64
데이터갱신구분     169 non-null object
데이터갱신일자     169 non-null object
업태구분명       169 non-null object
좌표정보(X)     169 non-null float64
좌표정보(Y)     169 non-null float64
위생업태명       169 non-null object
다중이용업소여부    169 non-null object
시설총규모       169 non-null float64
dtypes: float64(4), int64(4), object(11)
memory usage: 25.2+ KB

In [91]:
missing = busan_food_cafe.shape[0] - busan_food_cafe.count()

In [92]:
missing

개방서비스명        0
인허가일자         0
영업상태구분코드      0
영업상태명         0
상세영업상태코드      0
상세영업상태명       0
폐업일자        105
소재지면적         4
소재지전체주소       0
사업장명          0
최종수정시점        0
데이터갱신구분       0
데이터갱신일자       0
업태구분명         0
좌표정보(X)       0
좌표정보(Y)       0
위생업태명         0
다중이용업소여부      0
시설총규모         0
dtype: int64

In [93]:
busan_food_cafe.to_csv('../Staging_Tables/busan_food_cafe.csv', encoding = 'euc-kr')